/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExercicesRouteImport } from './routes/exercices'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadAvatarRouteImport } from './routes/api/upload-avatar'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthTherapistIndexRouteImport } from './routes/_auth/therapist/index'
import { Route as AuthPatientIndexRouteImport } from './routes/_auth/patient/index'
import { Route as ApiProfileUpdateRouteImport } from './routes/api/profile/update'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProfileUpdateServerRouteImport } from './routes/api/profile/update.server'
import { Route as ApiAuthChangePasswordServerRouteImport } from './routes/api/auth/change-password.server'
import { Route as AuthTherapistPatientsPatientIdRouteImport } from './routes/_auth/therapist/patients/$patientId'
import { Route as ApiProfileAvatarDeleteServerRouteImport } from './routes/api/profile/avatar/delete.server'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesRoute = ExercicesRouteImport.update({
  id: '/exercices',
  path: '/exercices',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadAvatarRoute = ApiUploadAvatarRouteImport.update({
  id: '/api/upload-avatar',
  path: '/api/upload-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTherapistIndexRoute = AuthTherapistIndexRouteImport.update({
  id: '/therapist/',
  path: '/therapist/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPatientIndexRoute = AuthPatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => AuthRoute,
} as any)
const ApiProfileUpdateRoute = ApiProfileUpdateRouteImport.update({
  id: '/api/profile/update',
  path: '/api/profile/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileUpdateServerRoute = ApiProfileUpdateServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => ApiProfileUpdateRoute,
} as any)
const ApiAuthChangePasswordServerRoute =
  ApiAuthChangePasswordServerRouteImport.update({
    id: '/server',
    path: '/server',
    getParentRoute: () => ApiAuthChangePasswordRoute,
  } as any)
const AuthTherapistPatientsPatientIdRoute =
  AuthTherapistPatientsPatientIdRouteImport.update({
    id: '/therapist/patients/$patientId',
    path: '/therapist/patients/$patientId',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiProfileAvatarDeleteServerRoute =
  ApiProfileAvatarDeleteServerRouteImport.update({
    id: '/api/profile/avatar/delete/server',
    path: '/api/profile/avatar/delete/server',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercices': typeof ExercicesRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRouteWithChildren
  '/api/profile/update': typeof ApiProfileUpdateRouteWithChildren
  '/patient': typeof AuthPatientIndexRoute
  '/therapist': typeof AuthTherapistIndexRoute
  '/therapist/patients/$patientId': typeof AuthTherapistPatientsPatientIdRoute
  '/api/auth/change-password/server': typeof ApiAuthChangePasswordServerRoute
  '/api/profile/update/server': typeof ApiProfileUpdateServerRoute
  '/api/profile/avatar/delete/server': typeof ApiProfileAvatarDeleteServerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercices': typeof ExercicesRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRouteWithChildren
  '/api/profile/update': typeof ApiProfileUpdateRouteWithChildren
  '/patient': typeof AuthPatientIndexRoute
  '/therapist': typeof AuthTherapistIndexRoute
  '/therapist/patients/$patientId': typeof AuthTherapistPatientsPatientIdRoute
  '/api/auth/change-password/server': typeof ApiAuthChangePasswordServerRoute
  '/api/profile/update/server': typeof ApiProfileUpdateServerRoute
  '/api/profile/avatar/delete/server': typeof ApiProfileAvatarDeleteServerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/exercices': typeof ExercicesRoute
  '/login': typeof LoginRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/api/upload-avatar': typeof ApiUploadAvatarRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/change-password': typeof ApiAuthChangePasswordRouteWithChildren
  '/api/profile/update': typeof ApiProfileUpdateRouteWithChildren
  '/_auth/patient/': typeof AuthPatientIndexRoute
  '/_auth/therapist/': typeof AuthTherapistIndexRoute
  '/_auth/therapist/patients/$patientId': typeof AuthTherapistPatientsPatientIdRoute
  '/api/auth/change-password/server': typeof ApiAuthChangePasswordServerRoute
  '/api/profile/update/server': typeof ApiProfileUpdateServerRoute
  '/api/profile/avatar/delete/server': typeof ApiProfileAvatarDeleteServerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercices'
    | '/login'
    | '/profile'
    | '/api/upload-avatar'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/profile/update'
    | '/patient'
    | '/therapist'
    | '/therapist/patients/$patientId'
    | '/api/auth/change-password/server'
    | '/api/profile/update/server'
    | '/api/profile/avatar/delete/server'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercices'
    | '/login'
    | '/profile'
    | '/api/upload-avatar'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/profile/update'
    | '/patient'
    | '/therapist'
    | '/therapist/patients/$patientId'
    | '/api/auth/change-password/server'
    | '/api/profile/update/server'
    | '/api/profile/avatar/delete/server'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/exercices'
    | '/login'
    | '/_auth/profile'
    | '/api/upload-avatar'
    | '/api/auth/$'
    | '/api/auth/change-password'
    | '/api/profile/update'
    | '/_auth/patient/'
    | '/_auth/therapist/'
    | '/_auth/therapist/patients/$patientId'
    | '/api/auth/change-password/server'
    | '/api/profile/update/server'
    | '/api/profile/avatar/delete/server'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ExercicesRoute: typeof ExercicesRoute
  LoginRoute: typeof LoginRoute
  ApiUploadAvatarRoute: typeof ApiUploadAvatarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRouteWithChildren
  ApiProfileUpdateRoute: typeof ApiProfileUpdateRouteWithChildren
  ApiProfileAvatarDeleteServerRoute: typeof ApiProfileAvatarDeleteServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices': {
      id: '/exercices'
      path: '/exercices'
      fullPath: '/exercices'
      preLoaderRoute: typeof ExercicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-avatar': {
      id: '/api/upload-avatar'
      path: '/api/upload-avatar'
      fullPath: '/api/upload-avatar'
      preLoaderRoute: typeof ApiUploadAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/therapist/': {
      id: '/_auth/therapist/'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof AuthTherapistIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/patient/': {
      id: '/_auth/patient/'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof AuthPatientIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/profile/update': {
      id: '/api/profile/update'
      path: '/api/profile/update'
      fullPath: '/api/profile/update'
      preLoaderRoute: typeof ApiProfileUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/update/server': {
      id: '/api/profile/update/server'
      path: '/server'
      fullPath: '/api/profile/update/server'
      preLoaderRoute: typeof ApiProfileUpdateServerRouteImport
      parentRoute: typeof ApiProfileUpdateRoute
    }
    '/api/auth/change-password/server': {
      id: '/api/auth/change-password/server'
      path: '/server'
      fullPath: '/api/auth/change-password/server'
      preLoaderRoute: typeof ApiAuthChangePasswordServerRouteImport
      parentRoute: typeof ApiAuthChangePasswordRoute
    }
    '/_auth/therapist/patients/$patientId': {
      id: '/_auth/therapist/patients/$patientId'
      path: '/therapist/patients/$patientId'
      fullPath: '/therapist/patients/$patientId'
      preLoaderRoute: typeof AuthTherapistPatientsPatientIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/profile/avatar/delete/server': {
      id: '/api/profile/avatar/delete/server'
      path: '/api/profile/avatar/delete/server'
      fullPath: '/api/profile/avatar/delete/server'
      preLoaderRoute: typeof ApiProfileAvatarDeleteServerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
  AuthPatientIndexRoute: typeof AuthPatientIndexRoute
  AuthTherapistIndexRoute: typeof AuthTherapistIndexRoute
  AuthTherapistPatientsPatientIdRoute: typeof AuthTherapistPatientsPatientIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
  AuthPatientIndexRoute: AuthPatientIndexRoute,
  AuthTherapistIndexRoute: AuthTherapistIndexRoute,
  AuthTherapistPatientsPatientIdRoute: AuthTherapistPatientsPatientIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiAuthChangePasswordRouteChildren {
  ApiAuthChangePasswordServerRoute: typeof ApiAuthChangePasswordServerRoute
}

const ApiAuthChangePasswordRouteChildren: ApiAuthChangePasswordRouteChildren = {
  ApiAuthChangePasswordServerRoute: ApiAuthChangePasswordServerRoute,
}

const ApiAuthChangePasswordRouteWithChildren =
  ApiAuthChangePasswordRoute._addFileChildren(
    ApiAuthChangePasswordRouteChildren,
  )

interface ApiProfileUpdateRouteChildren {
  ApiProfileUpdateServerRoute: typeof ApiProfileUpdateServerRoute
}

const ApiProfileUpdateRouteChildren: ApiProfileUpdateRouteChildren = {
  ApiProfileUpdateServerRoute: ApiProfileUpdateServerRoute,
}

const ApiProfileUpdateRouteWithChildren =
  ApiProfileUpdateRoute._addFileChildren(ApiProfileUpdateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ExercicesRoute: ExercicesRoute,
  LoginRoute: LoginRoute,
  ApiUploadAvatarRoute: ApiUploadAvatarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRouteWithChildren,
  ApiProfileUpdateRoute: ApiProfileUpdateRouteWithChildren,
  ApiProfileAvatarDeleteServerRoute: ApiProfileAvatarDeleteServerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
